### ISSUE TITLE
Output JSON format in `json-timeline` for standard output

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1197]
When outputting to standard output with the `json-timeline` command the results are the same as `csv-timeline`, however, it would be nice to output in JSON format for quick testing when creating rules, etc.. 
[colored_json](https://github.com/ctron/colored_json) looks like a good crate to use as I would like to output in color to make easier to read.

**Comment by hitenkoku** [comment]
@YamatoSecurity Thanks for creating issue.
I implemented json-timeline and jsonl-timeline  standard I/O with `colored-json` crate.
because output of `json-output` each record to reduce memory usage, formatted json outputting is difficult.

```
> ./1197.exe json-timeline -d ../hayabusa-sample-evtx -w 
```

<img width="1208" alt="image" src="https://github.com/Yamato-Security/hayabusa/assets/2350416/ae944c07-993d-4914-9b47-ebc04b2bda2a">

**Comment by hitenkoku** [comment]
<img width="1206" alt="image" src="https://github.com/Yamato-Security/hayabusa/assets/2350416/0f8adf34-56bf-46ce-b718-959b4c24208b">
