### ISSUE TITLE
Add RDP logon/logoff info to `logon-summary`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#1468]
Reference:
https://github.com/Yamato-Security/hayabusa/discussions/1391

**Comment by fukusuket** [comment]
https://jpcertcc.github.io/ToolAnalysisResultSheet_jp/details/mstsc.htm

**Comment by fukusuket** [comment]
@YamatoSecurity 
I have four questions! What do you think?

1.  Is it correct to add only `RDS-LSM EID:21`? (I think that `RDS EID:25` is unnecessary because of the reconnection log)
2.  Should I also add `RDS Gateway EID: 302`? 
3.  Should I add a `Channel` column? Or should I not add it?
4.  The username format in the RDS log is `domain/username`. should I just output `username`?

**Comment by YamatoSecurity** [comment]
Good questions!
1. Yes, I think for the `logon-summary` command we should just use the RDS-LSM 21 events and ignore reconnect events.
2. Yes, lets add `RDS Gateway 302`
3. Lets add an `Event` column and put `Sec 4624`, `RDS Gateway 302`, `RDS-LSM 21`, etc... in it
4. Lets just add the `username` part but lets add another `Target Domain` and `Source Domain` columns and put the domain names in there. We can use `TargetDomainName` and `SubjectDomainName` fields. We should probably add a `Source User` column as well with the `SubjectUserName` field information.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much for checking! I'll implement prototype!💪 (One concern is whether it will fit on one screen, but we will check this with a prototype!)
