### ISSUE TITLE
Weird characters in Excel File results? 

### ISSUE THREAD

**Issue by mathurin68** [Yamato-Security/hayabusa#743]
This is just awesome, thank you so much for building this!  I'm sure this is just something dumb I'm doing but... 
I'm getting these weird 'accents' in my excel file
![image](https://user-images.githubusercontent.com/5932961/195367794-23674bfe-7b7c-45a3-ba25-9466e7563e5f.png)

**Comment by YamatoSecurity** [comment]
Thanks for reporting this. We use the broken pipe as delimeters. I tested it out and it works on my environment.
You are displaying the broken pipe correctly so I don't think it is a font issue.
<img width="186" alt="Screen Shot 2022-10-13 at 6 38 26" src="https://user-images.githubusercontent.com/71482215/195453092-af62f0f3-b658-4e55-9b0a-08e1070446e7.png">
Can you try importing into Excel again using `UTF-8`? I am guessing that you imported with a different encoding.

**Comment by fukusuket** [comment]
In my environment, opening the CSV file directly in Excel (**not importing**),  similar issue will occur as follows
(Due to Excel specifications, **UTF-8 CSV without BOM** cannot be read correctly)

<img width="504" alt="mojibake" src="https://user-images.githubusercontent.com/41001169/195640418-630abfa2-f7aa-451b-83b1-cd3df7ace66a.png">

but save it again with **UTF8-BOM** 
<img width="459" alt="save-with-utf8bom" src="https://user-images.githubusercontent.com/41001169/195641377-78b2966d-23d4-4c47-970e-716ede740521.png">

and reopening it will solve it as follows, how about it?
<img width="490" alt="mojibake-resolved" src="https://user-images.githubusercontent.com/41001169/195641392-3a44ce89-c756-49e7-8230-dc3fc01b0789.png">

Or you can solve it by following **import** steps.
https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-utf-8-csv-file-in-excel-without-mis/1eb15700-d235-441e-8b99-db10fafff3c2

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks for checking this out for us! I will try to add to the Excel import instructions.

**Comment by mathurin68** [comment]
Thank you for these suggestions!!!  Unfortunately, I couldn't get any of them to work, but I'm gonna play around some more this weekend.  I tried the link and suggestions above, I even tried the following powershell with no success. 
 
`Get-Content .\Verbose_Results.csv | set-Content -Encoding utf8 .\Verbose_Results2.txt`

I'll keep trying this weekend, and thanks again!

**Comment by YamatoSecurity** [comment]
@mathurin68 Thanks for letting us know. I am not sure if you have to install some multi-lingual package or something. We will keep this issue open until hopefully someone finds a fix. Please let us know if you figure it out.

**Comment by fukusuket** [comment]
@mathurin68  Thanks for comment :) I did a little research... 
When I tried the python code below, 
```Python3
print("¦".encode("UTF8")) # This is expected character.
print("ﾂｦ".encode("CP932"))  # My environment(Japanese Windows Default encoding)
print("Â¦".encode("CP1252"))  # mathurin68 environment?(European Windows Default encoding?)
```
then output is as follows. (all outputs were the same!)
```
b'\xc2\xa6'
b'\xc2\xa6'
b'\xc2\xa6'
```
Based on the above, I think it's likely that your Excel is reading CSV files with CP1252(or similar) encoding?(sorry if i misunderstood)

and If you're using PowerShell version 6 or higher, you may need to explicitly specify **utf8NoBOM**(not utf8)
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.2#character-encoding-in-powershell

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks so much!
@mathurin68 Can you tell us if `Get-Content -Encoding utf8BOM .\Verbose_Results.csv` works for you?

**Comment by mathurin68** [comment]
I finally have some time to go back to this.  

Ugh!!! Sorry, I must have been too tired or blind the night I tried all these, and missed this suggestion. 

This link, from @fukusuket suggestion above worked perfectly!
https://answers.microsoft.com/en-us/msoffice/forum/all/how-to-open-utf-8-csv-file-in-excel-without-mis/1eb15700-d235-441e-8b99-db10fafff3c2

Thank you all for your patience, help, and this amazing tool!!
