### ISSUE TITLE
[bug] Hayabusa may occasionally hangs on Windows

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/hayabusa#867]
**Describe the bug**
About 1 out of 10 times hayabuse.exe hangs when analyzing [large evtxes(6.1GB evtx)](https://github.com/Yamato-Security/hayabusa/issues/778#issuecomment-1296504766). 
At first I thought it was a hardware problem on my PC, but it happened on another PC, so I'm reporting this issue.

**Step to Reproduce**
Repeat the following steps about 10 times on Windows 10.

1. Launch task manager(Check for changes in CPU usage)
2. Launch Command prompt
3. hayabusa.exe -d [large evtx(6.1GB evtx)](https://github.com/Yamato-Security/hayabusa/issues/778#issuecomment-1296504766) -o out.csv
4. Check CPU usage in Task Manager

then about 1 out of 10 times hayabuse.exe hangs.

**Screenshots**
hayabusa does not use any CPU/Mem/Disk resources and hangs as below and the analysis never ends.
![error](https://user-images.githubusercontent.com/41001169/211134153-82d9c1a0-1894-4355-b406-0b2933a04cfc.png)

**Additional context**
But after above hang, pressing `Enter key` in console restarts analysis process.
So it may be a problem of Progressbar or Windows standard output ... ?🤔

**Environment (please complete the following information):**

- OS: Windows 10 Home/Pro edition (This issue happened on two different machines.)
- hayabusa version 1.9.0 (I haven't checked, but it may also occur in other versions)

I will continue to investigate reproduction conditions and versions.

**Comment by YamatoSecurity** [comment]
<img width="658" alt="Screen Shot 2023-01-07 at 5 48 36 PM" src="https://user-images.githubusercontent.com/71482215/211142218-b7d7868d-3906-4644-92d2-b9bdfd729702.png">

I had a similar problem when running on Mac but found out that it was due to Mac's sleeping function. I often use Hayabusa in the background so I turn off the display but it pause Hayabusa. I fixed it by checking the "Prevent your Mac from automatically sleeping when the display is off". I think you can also use the `caffeinate` command.

This is probably a different issue but just to be sure, you have the display running the whole time? Maybe there is a similar issue on your Windows environment where the OS is stopping it for some reason?
Does it happen with Windows Terminal as well or just Command Prompt?

**Comment by fukusuket** [comment]
Thank you for the information!  I see, it looks like a similar problem ... 🤔
 
In my case, this issue occurs under the following conditions.
 - I have the display running the whole time.
 - Command Prompt.

I will check if it also happens in Windows Terminal or Powershell. 
Also, I'll check if any sleep settings in the OS are affecting it.

**Comment by fukusuket** [comment]
Sorry! It was caused by the spec of Windows Command Prompt😅
I reproduced it with the following steps.

1. Launch task manager(Check for changes in CPU usage)
2. Launch Command prompt
3. hayabusa.exe -d large evtx(6.1GB evtx) -o out.csv
4. Left-click on the command prompt **as soon as the Progressbar appears**
5. then CPU usage become 0%

It was caused by the specification that clicking make the command prompt  edit mode and interrupts the program.
ref: https://softantenna.com/blog/windows-10-command-prompt-no-stop/

close the issue because it was not Hayabusa's bug.
