### ISSUE TITLE
hayabusa-2.1.0-win-x64.exe Option::unwrap() panic

### ISSUE THREAD

**Issue by mgreen27** [Yamato-Security/hayabusa#914]
**Describe the bug**
Looks like we have a bug in hayabusa-2.1.0-win-x64.exe when we run in Velociraptor. We run the csv-timeline with --live-analysis switches.

**Step to Reproduce**
`hayabusa-2.1.0-win-x64.exe csv-timeline --live-analysis --output "C:\Program Files\Velociraptor\gui\temp\output\hayabusa_results_94220472549.csv" --min-level informational --profile standard --quiet --no-summary --thread-number 2 --UTC`

**Expected behavior**
CSV is generated

**Environment (please complete the following information):**

- OS: Windows 10
- hayabusa version hayabusa-2.1.0-win-x64.exe

**Additional context**
![image](https://user-images.githubusercontent.com/13081800/217960678-432e19f5-76a3-4999-953a-d509db7f37df.png)

**Comment by hitenkoku** [comment]
@mgreen27  Thanks for your reporting.

After reviewing the error, It seems to be due to the fact that the meta information could not be retrieved when the file size information was being retrieved. It is possible that the target file was deleted or renamed after the list of target files was compiled.

In order to check in more detail, would you please try typing the following command and bring up the output?

` hayabusa-2.1.0-win-x64.exe csv-timeline --live-analysis --verbose --output "C:\Program Files\Velociraptor\gui\temp\output\hayabusa_results_94220472549.csv" --min-level informational --profile standard --quiet --no-summary --thread-number 2 --UTC  `

**Comment by mgreen27** [comment]
here are the results of the --verbose switch aded ![image](https://user-images.githubusercontent.com/13081800/217975475-ab0e5bb9-767c-4fb8-85c5-f2061813592e.png)

**Comment by YamatoSecurity** [comment]
@mgreen27 Thank you for reporting the issue. We have not seen this before.
@hitenkoku has created a patch that hopefully fixes your issue but as we can not reproduce the error, is it possible for you to test it for us? https://github.com/Yamato-Security/hayabusa/pull/915
We can provide a zip of the binary and needed files for you if that is easier.

By the way, if this does not work, can you try copying all of the windows event logs to a temporary directory and use Hayabusa with the `-d` directory option against that directory to see if it works? Since we are scanning files on a live system there may be issues since the logs are changing in real time. Although it is weird that it is crashing at that point.
You do not have any atypical environment where .evtx files are frequently created, deleted, etc.. in `C:\Windows\System32\winevt\Logs`, correct?

**Comment by mgreen27** [comment]
thank you for that - can you share where I can grab the compiled binary to test with? Im not familiar with your build process and couldnt find it :)

I can confirm -d <PATH> works on my version that is throwing the error so it just seems its the --live-analysis option i the issue.

**Comment by fukusuket** [comment]
What do you have set for the following event log retention settings?
https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-r2-and-2008/cc721981(v=ws.11)

IMHO, if `archive log when full, do not overwrite events` is set, the following sequence can also cause this issue ...🤔
1. Get target evtx file list. [src/main.rs#L758](https://github.com/Yamato-Security/hayabusa/blob/v2.1.0/src/main.rs#L758)
2. evtx reaches maximum file size and is archived (renamed ?)
3. Get evtx file metadata. [src/main.rs#L880](https://github.com/Yamato-Security/hayabusa/blob/v2.1.0/src/main.rs#L880)
    3.1 panic because of the [GetFileInformationByHandle error?](https://doc.rust-lang.org/std/fs/fn.metadata.html#platform-specific-behavior)

Even if the above archive settings are not used, an [GetFileInformationByHandle error](https://doc.rust-lang.org/std/fs/fn.metadata.html#platform-specific-behavior) may occur temporarily in an environment where a large amount of data is written to evtx...?

**Comment by YamatoSecurity** [comment]
Sorry, this was closed with the recent PR but will keep it open until confirmed to be resolved.

**Comment by YamatoSecurity** [comment]
@mgreen27 Sorry our unstable binary build process is kind of a manual process at the moment. You can test it with this: https://www.dropbox.com/s/v0opnkw5k9tnvco/Hayabusa-2.2.0-dev.zip?dl=0

Please let us know the output including the `--verbose` flag.

**Comment by mgreen27** [comment]
Hi all - the PR fixed the issue --verbose command ran through processing and output the csv as expected.

I did have to change the CLI slightly replacing "--thread-number 2" with "--threads 2".

I could not find any retention discrepencies. Here is a result common accross the few logs I tested
![image](https://user-images.githubusercontent.com/13081800/218259680-891121a6-6080-4ebf-a084-39ae0f97b9a6.png)
This machine is pretty old and I do RE and dev on it clearing logs reguarly, so most likley not a typical system :)

**Comment by mgreen27** [comment]
Thank you for your prompt fix :)

**Comment by fukusuket** [comment]
Thanks for the reply :)
It could not be reproduced even if Hayabusa(2.1.0) was executed under high load with the PowerShell script such as :
```
# Clear Log many times(by powershell)
while (1) { Clear-EventLog "Application" }

# Clear Log many times(by wevtutil)
while (1) { wevtutil el | Foreach-Object {wevtutil cl "$_"} }

# Write Log many times
while (1) { Write-EventLog -LogName "Application" -Source "Application" -EventID 2001 -EntryType Information -Message "MyApp added a user-requested feature to the display." -Category 1 -RawData 10,20 }
```
Also, the issue was not reproducible even when one of the following `Log Retention Policy` was met:
- `Overwrite events as needed.`
- `Archive the log when full, do not overwrite events.`

So it seems there are other reproduction conditions... 🤔
If I find out anything in the future, I will leave a comment as a memo.

**Comment by YamatoSecurity** [comment]
@mgreen27 
Glad to hear that the issue was fixed. We would still like to figure out what caused it though. If Hayabusa created any error logs or error messages with `--verbose`, could you share them with us?

> Hi all - the PR fixed the issue --verbose command ran through processing and output the csv as expected.
