### ISSUE TITLE
Create developer's guide for performance enhancements

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/hayabusa#928]
I would like to create some documentation about Rust performance for future developers as well as Rust programmers interested in making their programs very fast and memory efficient.
We can put it under `doc/RustPerformance-English.md` and `doc/RustPerformance-Japanese.md`.
@fukusuket Could I ask you to write the first draft? (No hurry, so whenever you have extra time.)
You can just document all of your performance enhancements you made recently in Japanese and I can handle the English translations when it is finished.
I would like to include the old sample code versus new sample code and roughly how much it improves speed and/or memory.
Maybe group by category. For example:
1. Avoid regular expressions as much as possible. Here are some ways that we filter with String comparisons first, etc..
2. Use [Iterators](https://doc.rust-lang.org/std/iter/trait.Iterator.html) instead of [Vec](https://doc.rust-lang.org/std/vec/struct.Vec.html).
Iterators can reduce memory usage because memory allocation only occurs one record at a time.
Also, change the return type to Box<dyn Iterator> to make Iterator the return value of the function.
Iterator is trait (not structs), so need to be wrapped in a Box to return from a function
3. Avoid using clone
4. Use compactstr to avoid heap allocation
5. Use mimalloc for Windows, xxx for linux/mac
6. etc...

What do you think?

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much! I will assign you then.
Indeed, we should probably explain how we are measuring performance. Recently I have been putting my benchmarks in your pull requests and noting them in the changelog as well. We can use your or my benchmarks. I don't think it has to be perfect measurements. Just as long as we give people an idea of how much performance changed in our project.

**Comment by fukusuket** [comment]
memo:

## Category of performance improvement

### Memory

####  by removing unnecessary fields and string
  - https://github.com/Yamato-Security/hayabusa/pull/806
  - https://github.com/Yamato-Security/hayabusa/pull/837
  - https://github.com/Yamato-Security/hayabusa/pull/894

####  by reducing clone() and to_string()
  - https://github.com/Yamato-Security/hayabusa/pull/793

####  by using iterator instead of vec
  - https://github.com/Yamato-Security/hayabusa/pull/921
  - https://github.com/Yamato-Security/hayabusa/pull/906

####  by using external crate
  - https://github.com/Yamato-Security/hayabusa/pull/793

####  by changing global memory allocator(mimalloc)
  - https://github.com/Yamato-Security/hayabusa/pull/777

### Speed

####  by reducing IO process
  - https://github.com/Yamato-Security/hayabusa/pull/858

####  by changing regex match to std:string method match
  - https://github.com/Yamato-Security/hayabusa/pull/882
  - https://github.com/Yamato-Security/hayabusa/pull/883
  - https://github.com/Yamato-Security/hayabusa/pull/884
  - https://github.com/Yamato-Security/hayabusa/pull/890

####  by changing global memory allocator(mimalloc)
  - https://github.com/Yamato-Security/hayabusa/pull/777

### Benchmarking

- heaptrack
  - https://medium.com/lumen-engineering-blog/tutorial-profiling-cpu-and-ram-usage-of-rust-micro-services-running-on-kubernetes-fbc32714da93
  - https://www.brendangregg.com/flamegraphs.html
- mimalloc-stats
  - https://github.com/Yamato-Security/hayabusa/pull/822
- about memory layout
  - https://www.youtube.com/watch?v=rDoqT-a6UFg
  - https://doc.rust-lang.org/std/mem/fn.size_of.html

### Reference 
#### Rust performance guide
- https://nnethercote.github.io/perf-book/introduction.html

#### enum vs trait 
- https://users.rust-lang.org/t/performance-implications-of-box-trait-vs-enum-delegation/11957
- https://github.com/Britefury/rust-enum-vs-trait-benchmark
- https://www.possiblerust.com/guide/enum-or-trait-object
- https://qiita.com/taiki-e/items/39688f6c86b919988222
- https://qiita.com/carrotflakes/items/896ce7f49931c64a2954

**Comment by fukusuket** [comment]
@YamatoSecurity 
I'm starting to write a performance guide on [this branch](https://github.com/Yamato-Security/hayabusa/blob/doc-hayabusa-developer-performance-guide/doc/RustPerformance-Japanese.md).
I'm thinking of writing with the above structure,🤔 what do you think? I would appreciate it if you could comment if there is anything that should be changed in the paragraph. 🙏 (It's still a draft of a draft, so anything can be changed :) )

**Comment by YamatoSecurity** [comment]
@fukusuket Looks great!
What about changing the order from 1. メモリ使用量の削減 2. 速度の改善 3. ベンチマークの取得 to 1. 速度の改善 2. メモリ使用量の削減 3. ベンチマークの取得 ?
I think this might be better as most people want to hear about speed improvements first and 2 & 3 go together more. (reducing memory and checking with benchmarks)
Everything else looks great. 
It would be nice to have a screenshot of the mimalloc --debug output and explain which numbers are the most important and how the latest version of mimalloc seems to have a bug that gives results like -128GB but just to ignore that as MS needs to fix it.

**Comment by fukusuket** [comment]
Thank you for reviewing :) I'll update the order paragraphs and put a screenshot!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I have finished writing the Japanese version of the draft document on [this branch](https://github.com/Yamato-Security/hayabusa/blob/doc-hayabusa-developer-performance-guide/doc/RustPerformance-Japanese.md) :)
I would appreciate it if you could do a review and an English translation when you have time🙏

**Comment by YamatoSecurity** [comment]
@fukusuket Thank you so much! It might take a little while as I have to prepare for teaching SANS next week but can definitely do it after that. 

@hitenkoku Can you add whatever performance advice you have as well?

**Comment by hitenkoku** [comment]
@fukusuket Thank you for writing. It is very useful for me.

@YamatoSecurity  I have nothing to add.
