### ISSUE TITLE
Logon-summary: add Time-stamp to grid

### ISSUE THREAD

**Issue by giacomoconti1978** [Yamato-Security/hayabusa#987]
HI, i use a lot of time hayabusa with logon-summary, and i have this output:

![Immagine 2023-04-05 105447](https://user-images.githubusercontent.com/129933237/230032277-a10a1092-e133-4370-98c5-363e8501b049.png)
 there is a metod to add field %timestamp% for each searched evidence?

**Comment by YamatoSecurity** [comment]
Logon summary is just to find the total count of logons. If you want to get the timestamp of when a logon happened you would have to create CSV or JSON file and analyze that because the output would be so big you probably couldn't fit it on the screen. You can add `-r ./rules/hayabusa/builtin/Security/LogonLogoff/` to either the csv-timeline or json-timeline command to just run rules that lookup logons and logoffs.
Maybe I am not understanding what you are trying to do. It may be possible to add two columns to print just the first and last timestamp of logons.

**Comment by YamatoSecurity** [comment]
Are you looking for a logon timeline feature like we provide with WELA?
https://github.com/Yamato-Security/WELA/blob/main/Screenshots/Screenshot-LogonTimelineGUI.png

**Comment by giacomoconti1978** [comment]
Okay, with WELA I already get more results. I need to analyze the log files of a pc attacked by ransomware, exploiting exposed RDP. Can I use Hayabusa in some other way to look for evidence of external connections?

Thanks so much

**Comment by YamatoSecurity** [comment]
Yes, CSV and JSON output will give you the most evidence. You can analyze them with Timeline Explorer or jq. There is documentation on how to use them in the readme.

**Comment by YamatoSecurity** [comment]
You can use jq to extract out the SrcIP (Source IP) or TgtIP (Target IP) fields from multiple logon logs and use Geo IP information to quickly discover where and who connected to what. Please check the jq and GeoIP documentation for how to do this.
